-- Generated by `python3 -m search.bounded.generate_lean`.
-- manifest_content_sha256: 05aef719a7651c4e9a0f724fd3cced02912d7cb66e316dbf443fc68a276c51fa
-- receipt_file_sha256: ae4bacf3739d3015cf0c71ccbe7c9da249d29a7ac0514c79173ec23d3c89bc7b
-- candidate_archive_file_sha256: 273b5a53eab00a484bf77c71c78fa6eb76f92302492cb0633b6cfeb702b29ebe
-- published_frontier_content_sha256: 26377125f82e06e2fc15663cb5d60f6066ce13eff9716043d1c61c130182fc90
-- Do not edit this file by hand; regenerate it from the verified receipt and archive.

import BoundedCoordinate.GeneratedProblem

namespace BoundedCoordinate

def compositionalPublishedFrontierCoordinates : List (List Token) :=
  [
    [],
    [.A],
    [.A, .B],
    [.A, .B, .C],
    [.A, .B, .C, .D]
  ]

def opaquePublishedFrontierCoordinates : List (List Token) :=
  [
    [],
    [.A, .B, .C, .D]
  ]

end BoundedCoordinate
