-- Generated by `python3 -m search.bounded.generate_lean`.
-- manifest_content_sha256: 05aef719a7651c4e9a0f724fd3cced02912d7cb66e316dbf443fc68a276c51fa
-- Do not edit this file by hand; edit problem.json and regenerate it.

namespace BoundedCoordinate

inductive Token where
  | A
  | B
  | C
  | D
  deriving BEq, DecidableEq, Repr

def alphabet : List Token := [.A, .B, .C, .D]

def chunk : Token → List Bool
  | .A => [true, false]
  | .B => [false, true]
  | .C => [true, true]
  | .D => [false, false]

def target : List Bool := [true, false, false, true, true, true, false, false]

def witness : List Token := [.A, .B, .C, .D]

def compositionalDecode (coordinate : List Token) : List Bool :=
  coordinate.flatMap chunk

def opaqueDecode (coordinate : List Token) : List Bool :=
  if coordinate = witness then target else [false, false, false, false, false, false, false, false]

end BoundedCoordinate
