from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

from .model import ProblemManifest


HERE = Path(__file__).resolve().parent
DEFAULT_MANIFEST = HERE / "problem.json"
DEFAULT_OUTPUT = HERE / "lean" / "BoundedCoordinate" / "GeneratedProblem.lean"
DEFAULT_RECEIPT = HERE / "results" / "receipt.json"
DEFAULT_ARCHIVE = HERE / "results" / "candidates.jsonl"
DEFAULT_FRONTIER_OUTPUT = (
    HERE / "lean" / "BoundedCoordinate" / "GeneratedFrontier.lean"
)
LEAN_IDENTIFIER = re.compile(r"[A-Za-z][A-Za-z0-9_]*\Z")


def _identifier(token: str) -> str:
    if not LEAN_IDENTIFIER.fullmatch(token):
        raise ValueError(f"token {token!r} is not a supported Lean constructor name")
    return token


def _bool_list(bits: str) -> str:
    values = ["true" if bit == "1" else "false" for bit in bits]
    return f"[{', '.join(values)}]"


def _token_list(tokens: tuple[str, ...]) -> str:
    return f"[{', '.join(f'.{_identifier(token)}' for token in tokens)}]"


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _canonical_hash(value: object) -> str:
    serialized = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


def _coordinate_list(coordinates: list[tuple[str, ...]]) -> str:
    rows = ",\n".join(f"    {_token_list(coordinate)}" for coordinate in coordinates)
    return f"  [\n{rows}\n  ]"


def render_problem(manifest: ProblemManifest) -> str:
    constructors = "\n".join(
        f"  | {_identifier(token)}" for token in manifest.alphabet
    )
    chunk_cases = "\n".join(
        f"  | .{_identifier(token)} => {_bool_list(manifest.compositional_chunks[token])}"
        for token in manifest.alphabet
    )
    return f"""-- Generated by `python3 -m search.bounded.generate_lean`.
-- manifest_content_sha256: {manifest.manifest_hash}
-- Do not edit this file by hand; edit problem.json and regenerate it.

namespace BoundedCoordinate

inductive Token where
{constructors}
  deriving BEq, DecidableEq, Repr

def alphabet : List Token := {_token_list(manifest.alphabet)}

def chunk : Token → List Bool
{chunk_cases}

def target : List Bool := {_bool_list(manifest.target)}

def witness : List Token := {_token_list(manifest.opaque_witness)}

def compositionalDecode (coordinate : List Token) : List Bool :=
  coordinate.flatMap chunk

def opaqueDecode (coordinate : List Token) : List Bool :=
  if coordinate = witness then target else {_bool_list(manifest.opaque_fallback)}

end BoundedCoordinate
"""


def render_frontier(
    manifest: ProblemManifest,
    receipt: object,
    candidate_archive: object,
    *,
    receipt_file_sha256: str,
    archive_file_sha256: str,
) -> str:
    if not isinstance(receipt, dict):
        raise ValueError("receipt must be an object")
    if receipt.get("manifestContentSha256") != manifest.manifest_hash:
        raise ValueError("receipt manifest hash does not match the Lean problem")
    if not isinstance(candidate_archive, list) or not all(
        isinstance(point, dict) for point in candidate_archive
    ):
        raise ValueError("candidate archive must be a list of objects")
    by_id = {point.get("id"): point for point in candidate_archive}
    if len(by_id) != len(candidate_archive) or None in by_id:
        raise ValueError("candidate archive IDs must be present and unique")
    metadata = receipt.get("candidateArchive")
    if not isinstance(metadata, dict):
        raise ValueError("receipt candidateArchive metadata must be an object")
    if metadata.get("count") != len(candidate_archive):
        raise ValueError("candidate archive count does not match the receipt")
    if metadata.get("contentSha256") != _canonical_hash(candidate_archive):
        raise ValueError("candidate archive content hash does not match the receipt")
    if metadata.get("fileSha256") != archive_file_sha256:
        raise ValueError("candidate archive file hash does not match the receipt")

    frontier_records: dict[str, list[dict[str, object]]] = {}
    frontier_coordinates: dict[str, list[tuple[str, ...]]] = {}
    for landscape in ("compositional", "opaque"):
        try:
            candidate_ids = receipt["landscapeResults"][landscape][
                "representativeFrontier"
            ]["candidateIds"]
        except (KeyError, TypeError) as error:
            raise ValueError(f"missing {landscape} representative frontier") from error
        if not isinstance(candidate_ids, list) or not all(
            isinstance(candidate_id, str) for candidate_id in candidate_ids
        ):
            raise ValueError(f"{landscape} frontier IDs must be a list of strings")
        try:
            records = [by_id[candidate_id] for candidate_id in candidate_ids]
        except KeyError as error:
            raise ValueError(
                f"frontier references missing candidate {error.args[0]}"
            ) from error
        if any(record.get("landscape") != landscape for record in records):
            raise ValueError(f"{landscape} frontier contains a cross-landscape candidate")
        coordinates = []
        for record in records:
            coordinate = record.get("coordinate")
            if not isinstance(coordinate, list) or not all(
                isinstance(token, str) and token in manifest.alphabet
                for token in coordinate
            ):
                raise ValueError(f"{landscape} frontier has an invalid coordinate")
            coordinates.append(tuple(coordinate))
        frontier_records[landscape] = records
        frontier_coordinates[landscape] = coordinates

    frontier_hash = _canonical_hash(frontier_records)
    return f"""-- Generated by `python3 -m search.bounded.generate_lean`.
-- manifest_content_sha256: {manifest.manifest_hash}
-- receipt_file_sha256: {receipt_file_sha256}
-- candidate_archive_file_sha256: {archive_file_sha256}
-- published_frontier_content_sha256: {frontier_hash}
-- Do not edit this file by hand; regenerate it from the verified receipt and archive.

import BoundedCoordinate.GeneratedProblem

namespace BoundedCoordinate

def compositionalPublishedFrontierCoordinates : List (List Token) :=
{_coordinate_list(frontier_coordinates["compositional"])}

def opaquePublishedFrontierCoordinates : List (List Token) :=
{_coordinate_list(frontier_coordinates["opaque"])}

end BoundedCoordinate
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Lean definitions from the bounded problem.")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--receipt", type=Path, default=DEFAULT_RECEIPT)
    parser.add_argument("--archive", type=Path, default=DEFAULT_ARCHIVE)
    parser.add_argument("--frontier-out", type=Path, default=DEFAULT_FRONTIER_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    manifest = ProblemManifest.from_path(args.manifest)
    receipt = json.loads(args.receipt.read_text(encoding="utf-8"))
    candidate_archive = [
        json.loads(line)
        for line in args.archive.read_text(encoding="utf-8").splitlines()
        if line
    ]
    rendered = render_problem(manifest)
    rendered_frontier = render_frontier(
        manifest,
        receipt,
        candidate_archive,
        receipt_file_sha256=_sha256_file(args.receipt),
        archive_file_sha256=_sha256_file(args.archive),
    )
    if args.check:
        if not args.out.exists() or args.out.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"generated Lean definitions are stale: {args.out}")
        if (
            not args.frontier_out.exists()
            or args.frontier_out.read_text(encoding="utf-8") != rendered_frontier
        ):
            raise SystemExit(
                f"generated Lean frontier definitions are stale: {args.frontier_out}"
            )
        print(
            "generated Lean definitions: current "
            f"({args.out}, {args.frontier_out})"
        )
        return
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    args.frontier_out.parent.mkdir(parents=True, exist_ok=True)
    args.frontier_out.write_text(rendered_frontier, encoding="utf-8")
    print(f"generated Lean definitions: wrote {args.out}, {args.frontier_out}")


if __name__ == "__main__":
    main()
