from __future__ import annotations

import argparse
import re
from pathlib import Path

from .model import ProblemManifest


HERE = Path(__file__).resolve().parent
DEFAULT_MANIFEST = HERE / "problem.json"
DEFAULT_OUTPUT = HERE / "lean" / "BoundedCoordinate" / "GeneratedProblem.lean"
LEAN_IDENTIFIER = re.compile(r"[A-Za-z][A-Za-z0-9_]*\Z")


def _identifier(token: str) -> str:
    if not LEAN_IDENTIFIER.fullmatch(token):
        raise ValueError(f"token {token!r} is not a supported Lean constructor name")
    return token


def _bool_list(bits: str) -> str:
    values = ["true" if bit == "1" else "false" for bit in bits]
    return f"[{', '.join(values)}]"


def _token_list(tokens: tuple[str, ...]) -> str:
    return f"[{', '.join(f'.{_identifier(token)}' for token in tokens)}]"


def render_problem(manifest: ProblemManifest) -> str:
    constructors = "\n".join(
        f"  | {_identifier(token)}" for token in manifest.alphabet
    )
    chunk_cases = "\n".join(
        f"  | .{_identifier(token)} => {_bool_list(manifest.compositional_chunks[token])}"
        for token in manifest.alphabet
    )
    return f"""-- Generated by `python3 -m search.bounded.generate_lean`.
-- manifest_content_sha256: {manifest.manifest_hash}
-- Do not edit this file by hand; edit problem.json and regenerate it.

namespace BoundedCoordinate

inductive Token where
{constructors}
  deriving BEq, DecidableEq, Repr

def alphabet : List Token := {_token_list(manifest.alphabet)}

def chunk : Token → List Bool
{chunk_cases}

def target : List Bool := {_bool_list(manifest.target)}

def witness : List Token := {_token_list(manifest.opaque_witness)}

def compositionalDecode (coordinate : List Token) : List Bool :=
  coordinate.flatMap chunk

def opaqueDecode (coordinate : List Token) : List Bool :=
  if coordinate = witness then target else {_bool_list(manifest.opaque_fallback)}

end BoundedCoordinate
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Lean definitions from the bounded problem.")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = render_problem(ProblemManifest.from_path(args.manifest))
    if args.check:
        if not args.out.exists() or args.out.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"generated Lean definitions are stale: {args.out}")
        print(f"generated Lean definitions: current ({args.out})")
        return
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    print(f"generated Lean definitions: wrote {args.out}")


if __name__ == "__main__":
    main()
